DROP TABLE producto_X_factura CASCADE CONSTRAINTS;
DROP TABLE bitacora CASCADE CONSTRAINTS;
DROP TABLE factura CASCADE CONSTRAINTS;
DROP TABLE producto CASCADE CONSTRAINTS;
DROP TABLE categoria CASCADE CONSTRAINTS;
DROP TABLE metodo_pago CASCADE CONSTRAINTS;
DROP TABLE persona_X_telefono CASCADE CONSTRAINTS;
DROP TABLE telefono CASCADE CONSTRAINTS;
DROP TABLE persona CASCADE CONSTRAINTS;
DROP TABLE distrito CASCADE CONSTRAINTS;
DROP TABLE canton CASCADE CONSTRAINTS;
DROP TABLE provincia CASCADE CONSTRAINTS;
DROP TABLE pais CASCADE CONSTRAINTS;

CREATE TABLE pais (
    id_pais NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_pais VARCHAR(20),
    CONSTRAINT  pk_pais PRIMARY KEY (id_pais)
);

CREATE TABLE provincia (
    id_provincia NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_provincia VARCHAR(20),
    id_pais NUMBER(5),
    CONSTRAINT  pk_provincia PRIMARY KEY (id_provincia),
    CONSTRAINT fk_provincia_pais FOREIGN KEY (id_pais)
        REFERENCES pais(id_pais)
);

CREATE TABLE canton (
    id_canton NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_canton VARCHAR(20),
    id_provincia NUMBER(5),
    CONSTRAINT  pk_canton PRIMARY KEY (id_canton),
    CONSTRAINT fk_canton_provincia FOREIGN KEY (id_provincia)
        REFERENCES provincia(id_provincia)
);

CREATE TABLE distrito (
    id_distrito NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_distrito VARCHAR(20),
    id_canton NUMBER(5),
    CONSTRAINT  pk_distrito PRIMARY KEY (id_distrito),
    CONSTRAINT fk_distrito_canton FOREIGN KEY (id_canton)
        REFERENCES canton(id_canton)
);

CREATE TABLE persona (
    id_persona NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    isEmpleado NUMBER(1) CHECK (isEmpleado IN (0, 1)),
    nombre VARCHAR(20),
    apellido VARCHAR(20),
    correo_electronico VARCHAR(50),
    password_persona VARCHAR2(255),
    id_distrito NUMBER(5),
    CONSTRAINT pk_persona PRIMARY KEY (id_persona),
    CONSTRAINT fk_persona_distrito FOREIGN KEY (id_distrito)
        REFERENCES distrito(id_distrito)
);

CREATE TABLE telefono (
    id_telefono NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    numero VARCHAR(20),
    CONSTRAINT pk_telefono PRIMARY KEY (id_telefono)
);

CREATE TABLE persona_X_telefono (
    id_persona NUMBER(10),
    id_telefono NUMBER(10),
    CONSTRAINT pk_per_X_tel PRIMARY KEY (id_persona, id_telefono),
    CONSTRAINT fk_per_tel_persona FOREIGN KEY (id_persona)
        REFERENCES persona(id_persona),
    CONSTRAINT fk_per_tel_telefono FOREIGN KEY (id_telefono)
        REFERENCES telefono(id_telefono)
);

CREATE TABLE metodo_pago (
    id_metodo NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR(10),
    CONSTRAINT pk_metodo_pago PRIMARY KEY (id_metodo)
);

CREATE TABLE factura (
    id_factura NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_persona NUMBER(10),
    id_metodo NUMBER(10),
    total NUMBER(10),
    fecha DATE,
    CONSTRAINT pk_factura PRIMARY KEY (id_factura),
    CONSTRAINT fk_factura_persona FOREIGN KEY (id_persona)
        REFERENCES persona(id_persona),
    CONSTRAINT fk_factura_met_pag FOREIGN KEY (id_metodo)
        REFERENCES metodo_pago(id_metodo)
);

CREATE TABLE categoria (
    id_categoria NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR(20),
    descripcion VARCHAR(150),
    impuesto NUMBER(10, 4),
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria)
);

CREATE TABLE producto (
    id_producto NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR(100),
    precio NUMBER(10, 4),
    cantidad NUMBER(10),
    id_categoria NUMBER(10),
    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria)
);

CREATE TABLE producto_X_factura (
    id_producto NUMBER(10),
    id_factura NUMBER(10),
    cantidad_producto NUMBER(10),
    precio_unitario NUMBER(10,4),
    CONSTRAINT pk_prod_X_fact PRIMARY KEY (id_producto, id_factura),
    CONSTRAINT fk_prod_fact_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto),
    CONSTRAINT fk_prod_fact_factura FOREIGN KEY (id_factura)
        REFERENCES factura(id_factura)
);

CREATE TABLE bitacora (
    id_bitacora NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_producto NUMBER(10),
    precio_anterior NUMBER(10, 4),
    precio_nuevo NUMBER(10, 4),
    fecha_cambio DATE,
    CONSTRAINT pk_bitacora PRIMARY KEY (id_bitacora),
    CONSTRAINT fk_bitacora_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);

COMMIT;